# Generated by Django 5.1.5 on 2025-01-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exerciselog",
            old_name="exercise",
            new_name="exercise_type",
        ),
        migrations.AddField(
            model_name="exerciselog",
            name="calories_burned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exerciselog",
            name="duration_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exerciselog",
            name="heart_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="exerciselog",
            name="steps",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                ("details", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.userprofile",
                    ),
                ),
            ],
        ),
    ]
