# Generated by Django 5.1.5 on 2025-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicalvisit",
            options={"ordering": ["-visit_date"]},
        ),
        migrations.AlterModelOptions(
            name="exerciselog",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="steptracker",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="exerciselog",
            name="heart_rate",
        ),
        migrations.AlterField(
            model_name="steptracker",
            name="steps",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
