# Generated by Django 5.1.5 on 2025-01-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_clinicalvisit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steptracker",
            name="date",
            field=models.DateField(),
        ),
    ]
