# Generated by Django 5.1.5 on 2025-01-28 02:05

from django.db import migrations


def clean_duplicates(apps, schema_editor):
    StepTracker = apps.get_model('dashboard', 'StepTracker')
    
    # Get all records
    all_records = StepTracker.objects.all()
    seen = set()
    duplicate_ids = []
    
    # Find duplicates
    for record in all_records:
        key = (record.user_id, record.date)
        if key in seen:
            duplicate_ids.append(record.id)
        else:
            seen.add(key)
    
    # Delete duplicates
    StepTracker.objects.filter(id__in=duplicate_ids).delete()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_steptracker_date"),
    ]

    operations = []
