# Generated by Django 5.1.5 on 2025-01-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_clean_duplicate_steps"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="steptracker",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_user_date_step"
            ),
        ),
    ]
