# Generated by Django 5.1.5 on 2025-01-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_steptracker_unique_user_date_step"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exerciselog",
            options={},
        ),
        migrations.RemoveField(
            model_name="exerciselog",
            name="calories_burned",
        ),
        migrations.RemoveField(
            model_name="exerciselog",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="exerciselog",
            name="steps",
        ),
        migrations.AddField(
            model_name="hydrationlog",
            name="goal",
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name="hydrationlog",
            name="water_intake",
            field=models.FloatField(default=0.0),
        ),
    ]
