# Generated by Django 5.1.5 on 2025-01-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0009_alter_exerciselog_options_alter_hydrationlog_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passportcategory",
            options={"ordering": ["category_name"]},
        ),
        migrations.AddField(
            model_name="passportcategory",
            name="allergies",
            field=models.ManyToManyField(blank=True, to="dashboard.allergy"),
        ),
        migrations.AddField(
            model_name="passportcategory",
            name="doctors",
            field=models.ManyToManyField(blank=True, to="dashboard.doctor"),
        ),
        migrations.AddField(
            model_name="passportcategory",
            name="immunizations",
            field=models.ManyToManyField(blank=True, to="dashboard.immunization"),
        ),
        migrations.AddField(
            model_name="passportcategory",
            name="last_case_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passportcategory",
            name="medications",
            field=models.ManyToManyField(blank=True, to="dashboard.medication"),
        ),
        migrations.AddField(
            model_name="passportcategory",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("completed", "Completed")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="passportcategory",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
